// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentDemo.ScoreWebapi.Models;

namespace StudentDemo.ScoreWebapi.Migrations
{
    [DbContext(typeof(ScoreDbContext))]
    partial class ScoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StudentDemo.DominStd.Entities.ScoreModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Chinese")
                        .HasColumnType("int");

                    b.Property<int>("English")
                        .HasColumnType("int");

                    b.Property<int>("Maths")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("scores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Chinese = 126,
                            English = 41,
                            Maths = 58,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            Chinese = 121,
                            English = 81,
                            Maths = 109,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 3,
                            Chinese = 136,
                            English = 150,
                            Maths = 108,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 4,
                            Chinese = 77,
                            English = 79,
                            Maths = 52,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 5,
                            Chinese = 97,
                            English = 132,
                            Maths = 21,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 6,
                            Chinese = 108,
                            English = 63,
                            Maths = 132,
                            StudentId = 6
                        },
                        new
                        {
                            Id = 7,
                            Chinese = 53,
                            English = 120,
                            Maths = 76,
                            StudentId = 7
                        },
                        new
                        {
                            Id = 8,
                            Chinese = 142,
                            English = 26,
                            Maths = 29,
                            StudentId = 8
                        },
                        new
                        {
                            Id = 9,
                            Chinese = 132,
                            English = 23,
                            Maths = 75,
                            StudentId = 9
                        },
                        new
                        {
                            Id = 10,
                            Chinese = 54,
                            English = 43,
                            Maths = 63,
                            StudentId = 10
                        },
                        new
                        {
                            Id = 11,
                            Chinese = 103,
                            English = 114,
                            Maths = 55,
                            StudentId = 11
                        },
                        new
                        {
                            Id = 12,
                            Chinese = 88,
                            English = 31,
                            Maths = 87,
                            StudentId = 12
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
