// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentDemo.HubWebapi.Model;

namespace StudentDemo.HubWebapi.Migrations
{
    [DbContext(typeof(StudentDbcontext))]
    [Migration("20200813060433_AddStuData")]
    partial class AddStuData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StudentDemo.DominStd.Entities.StudentModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profession")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SClass")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("students");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Age = 20,
                            Name = "黎明",
                            Profession = "软件工程",
                            SClass = "软件1907"
                        },
                        new
                        {
                            ID = 2,
                            Age = 21,
                            Name = "小红",
                            Profession = "软件工程",
                            SClass = "软件1807"
                        },
                        new
                        {
                            ID = 3,
                            Age = 19,
                            Name = "黎明",
                            Profession = "软件工程",
                            SClass = "软件1907"
                        },
                        new
                        {
                            ID = 4,
                            Age = 20,
                            Name = "小明",
                            Profession = "软件工程",
                            SClass = "软件1907"
                        },
                        new
                        {
                            ID = 5,
                            Age = 22,
                            Name = "小黑",
                            Profession = "网络工程",
                            SClass = "软件1907"
                        },
                        new
                        {
                            ID = 6,
                            Age = 18,
                            Name = "黎明",
                            Profession = "网络工程",
                            SClass = "软件1907"
                        },
                        new
                        {
                            ID = 7,
                            Age = 21,
                            Name = "张三",
                            Profession = "网络工程",
                            SClass = "软件1707"
                        },
                        new
                        {
                            ID = 8,
                            Age = 21,
                            Name = "黎明",
                            Profession = "软件工程",
                            SClass = "软件1907"
                        },
                        new
                        {
                            ID = 9,
                            Age = 24,
                            Name = "李四",
                            Profession = "软件工程",
                            SClass = "软件1907"
                        },
                        new
                        {
                            ID = 10,
                            Age = 15,
                            Name = "王五",
                            Profession = "软件工程",
                            SClass = "软件1907"
                        },
                        new
                        {
                            ID = 11,
                            Age = 20,
                            Name = "孙八",
                            Profession = "软件工程",
                            SClass = "软件1907"
                        },
                        new
                        {
                            ID = 12,
                            Age = 20,
                            Name = "小六",
                            Profession = "软件工程",
                            SClass = "软件1907"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
